name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.22'
          
      - name: Prepare GO
        run: |
              rm -f go.mod
              rm -f go.sum
              go mod init github.com/xtls/libxray
              go mod tidy
              
      - name: Download GEO
        run: |
              go run main/main.go
              
      - name: Build .xcframework
        run: |
              rm -fr *.xcframework
              go install golang.org/x/mobile/cmd/gomobile@latest
              gomobile init
              go get -d golang.org/x/mobile/cmd/gomobile
              gomobile bind -target ios,iossimulator,macos -iosversion 15.0
              
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: ./LibXray.xcframework.zip
